spring:
  datasource:
    url: jdbc:h2:mem:tiny_task;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username:
    password:

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: validate

  h2:
    console:
      enabled: true

logging:
  level:
    com.coyoapp.tinytask: DEBUG
springdoc:
  swagger-ui:
    path: /docs

#server:
#  servlet:
#    context-path: /api
